# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ping-zxkit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ping-zxkit
	pod 'ZXKitCore', '~> 2.0'
	pod 'HDPingTools', '~> 2.0'
end
